# Generated by Django 2.0 on 2017-12-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, to='agenda.Curso'),
        ),
    ]
