# Generated by Django 2.0 on 2017-12-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20171209_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_disciplina', models.CharField(max_length=5, verbose_name='código da disciplina')),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='nome da disciplina')),
                ('periodo', models.CharField(max_length=2, verbose_name='período')),
                ('carga_horaria', models.CharField(max_length=4, verbose_name='carga horária')),
                ('bibliografia', models.TextField(max_length=500, verbose_name='bibliografia')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together={('cod_disciplina', 'nome_disciplina')},
        ),
    ]
