# Generated by Django 2.0 on 2017-12-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20171209_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'permissions': {(' manter_curso', 'Manter Curso')}},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'permissions': {(' manter_Disciplina', 'Manter Disciplina')}},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': {(' manter_professor', 'Manter professor')}},
        ),
        migrations.AlterModelOptions(
            name='semestre',
            options={'permissions': {(' manter_semestre', 'Manter Semestre')}},
        ),
    ]
