# Generated by Django 2.0 on 2017-12-13 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0005_auto_20171213_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoDisc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disciplinas', models.ManyToManyField(blank=True, null=True, to='agenda.Disciplina')),
            ],
        ),
    ]
